name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo $ENVIRONMENTSECRET
        name: deploy
        # ...deployment-specific steps

  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    needs: deploy-dev 
    steps:
      - run: echo $ENVIRONMENTSECRET
        name: deploy
        # ...deployment-specific steps

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test
    steps:
      - run: echo $ENVIRONMENTSECRET
        name: deploy
        # ...deployment-specific steps

